name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    with:
      mvnArgs: -DSKIP_UNIT_TESTS=false
    secrets:
      mvnArgs: |
       | sed -E "s|[0-9]. (WARNING) in ([^ ]*) \(at line ([0-9]+)\)(.*)|::\L\1 file=\2,line=\3::build issue\n\2@\3\4|g"\
       | sed -E "s|\[WARNING\] |::warning::|g"
